version: '2'
services:

  # Portainer Templates
  portainer-templates:
    image: portainer/templates
    container_name: "portainer-templates"
    volumes:
      - ${DIR}/templates2:/templates2

  # Portainer - to manage containers
  portainer:
    image: portainer/portainer
    restart: always
    container_name: "portainer-app"
    command: --templates http://templates/templates.json -d /data -H tcp://<DOCKER_HOST>:<DOCKER_PORT>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DIR}/portainer/data:/data
    ports:
      - 9000:9000

  # Plex media server
  plex:
    image: linuxserver/plex
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      VERSION: latest
    volumes:
      - ${DIR}/plex:/config
      - ${DIR}/media/movies:/media/movies
      - ${DIR}/media/tv:/media/tv
      - ${DIR}/media/transcode:/media/transcode
    tty: true
    ports:
      - 32400:32400
      - 32400:32400/udp
      - 32469:32469
      - 32469:32469/udp
      - 5353:5353/udp
      - 1900:1900/udp

  # Plex stats and metrics
  tautulli:
    image: linuxserver/tautulli
    depends_on:
      - plex
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      VERSION: latest
    volumes:
      - ${DIR}/tautulli:/config
    ports:
      - 8181:8181

  # App to keep track of all of the apps
  organizr:
    image: lsiocommunity/organizr
    depends_on:
      - plex
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      VERSION: latest
    volumes:
      - ${DIR}/organizr:/config
    ports:
      - 80:80

  # App for searching for and requesting media
  ombi:
    image: linuxserver/ombi
    depends_on:
      - plex
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      VERSION: latest
    volumes:
      - ${DIR}/ombi:/config
    ports:
      - 3579:3579

  # App for finding the correct Usenet movies to download
  sonarr:
    image: linuxserver/sonarr
    depends_on:
      - plex
      - sabnzbd
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      VERSION: latest
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      - ${DIR}/sonarr:/config
      - ${DIR}/media/tv:/tv
      - ${DIR}/media/downloads:/downloads
    ports:
      - 8989:8989

  # App for finding the correct Usenet tv shows to download
  radarr:
    image: linuxserver/radarr
    depends_on:
      - plex
      - sabnzbd
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      VERSION: latest
    volumes:
      - ${DIR}/radarr:/config
      - ${DIR}/media/movies:/movies
      - ${DIR}/media/downloads:/downloads
    ports:
      - 7878:7878

  # App for downloading media from Usenet
  sabnzbd:
    image: linuxserver/sabnzbd
    depends_on:
      - plex
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      VERSION: latest
    volumes:
      - ${DIR}/sabnzbd:/config
      - ${DIR}/media/downloads:/downloads
      - ${DIR}/media/incomplete-downloads:/incomplete-downloads
    ports:
      - 8080:8080
      - 9090:9090
